### ISSUE TITLE
ZSH completions are broken

### ISSUE THREAD

**Issue by Luxzi** [oberblastmeister/trashy#108]
When trying to autocomplete for files in a directory I get a ZSH completion parsing error (See below).

![image](https://github.com/oberblastmeister/trashy/assets/18560194/4b4d0d0b-906f-4de9-bd5c-562c7e1ef50b)

OS: Arch Linux
Package Version: 2.0.0-1
ZSH Version: 5.9-4

**Comment by AvianAnalyst** [comment]
I'm also getting this
OS: EndeavourOS
Same package, same ZSH 
zsh-completions 0.35.0-1

**Comment by AvianAnalyst** [comment]
@Luxzi This issue actually has gotten fixed in #103. You can get this fix from the trashy-get package in the aur.
