### ISSUE TITLE
More examples in help/man

### ISSUE THREAD

**Issue by roland-rollo** [oberblastmeister/trashy#30]
I feel puzzled how delete files from bin. I tried:

trash empty
```
error: Must match something
```

And then:
trash empty all
```
0 items will be emptied
╭───┬──────┬──────╮
│ i │ Time │ Path │
╰───┴──────┴──────╯
Are you sure? yes
```

But everything is still in trash folder. If you could add more info for people without imagination like me, that would be awesome.

**Comment by oberblastmeister** [comment]
It should be `trash empty --all` instead of `trash empty all`. I added an [example](https://github.com/oberblastmeister/trashy#restore-or-empty-all-files) to the readme.
