### ISSUE TITLE
Shorter name

### ISSUE THREAD

**Issue by oberblastmeister** [oberblastmeister/trashy#31]
`trash` is too long and doesn't match the project name `trashy`.

I'm thinking of changing the name to something shorter. Some ideas:
- `th`
- `ta`
- `tm`

**Comment by oberblastmeister** [comment]
I think I like `tm` the best.

**Comment by phocks** [comment]
`trash` matches other similar projects so I like it in that regard.

Putting this in your .bashrc should help.

`alias tm='trash'`

**Comment by VladimirMarkelov** [comment]
What does `m` mean in `tm`? management? `tm` for me looks like a short for `time`. Without extra explanation I would never call `trashy` as `tm`.
