### ISSUE TITLE
shell completions for fish shell don't complete for paths on `trash` command without `put`

### ISSUE THREAD

**Issue by m4rch3n1ng** [oberblastmeister/trashy#94]
pressing `<tab>` on the `trash` command only auto-completes for the commands, not the files in the directory. `trash put` completion works as expected.

i don't know how `"clap_complete"` works, but you can fix the completion by prepending the line `complete -c trash -F` to the automatically generated completions.

i only know about fish, but zsh still seems to be broken as of #57.

dropping `trash` in favor of `trash put` like suggested in https://github.com/oberblastmeister/trashy/issues/57#issuecomment-1458886458 would obviously work as well, but would be a major breaking change and the loss of a selling point.

**Comment by nahoj** [comment]
I'm in favor of dropping `trash <file>` if it helps provide reliable completion, I wrote why here: https://github.com/oberblastmeister/trashy/issues/57#issuecomment-1727298933.

**Comment by oberblastmeister** [comment]
Closed by #103
