### ISSUE TITLE
Error when using trash to delete something

### ISSUE THREAD

**Issue by GreenSleeper** [oberblastmeister/trashy#95]
I just installed `trash` using `cargo`, and when I run `trash something`, I get this error:
```
error: Error during a `trash` operation: Unknown { description: "Path: '\"/data01/.Trash-1009\"'. Message: Permission denied (os error 13)" }
```
What does it mean?
`/data01/.Trash-1009` desn't exist

**Comment by GreenSleeper** [comment]
And is there a way to configure the "trash folder"?

**Comment by elyashivhazan** [comment]
Hi, ur trying to delete a file in a external drive (not in ur home folder), their for by the [freedesktop.org](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html) specs it needs to be put in a folder named `/root_of_drive/.Trash-$UID` and u dont have permission to create that folder.

to fix change ur drive permission to allow u to create folders.

**Comment by rfourquet** [comment]
It looks like it should be enough for a `/root_of_drive/.Trash` directory to exist with appropriate permissions, in which case `/root_of_drive/.Trash/$UID` can be created and used as the trash directory.

**Comment by GreenSleeper** [comment]
> Hi, ur trying to delete a file in an external drive (not in ur home folder), their for by the [freedesktop.org](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html) specs it needs to be put in a folder named `/root_of_drive/.Trash-$UID` and u dont have permission to create that folder.
> 
> to fix change ur drive permission to allow u to create folders.

I only have permissions in one folder in that external drive, that why I asked if the trash folder could be configured.
anyway, thanks for your reply.
